apiVersion: v1
kind: Service
metadata:
  name: jogodavida-mpi-omp-server
spec:
  type: NodePort
  selector:
    app: jogodavida-mpi-omp-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090 